item {
  id: 1
  name: 'anorak'
  display_name: 'n0100001'
}
item {
  id: 2
  name: 'blazer'
  display_name: 'n0100002'
}
item {
  id: 3
  name: 'blouse'
  display_name: 'n0100003'
}
item {
  id: 4
  name: 'bomber'
  display_name: 'n0100004'
}
item {
  id: 5
  name: 'button-down'
  display_name: 'n0100005'
}
item {
  id: 6
  name: 'cardigan'
  display_name: 'n0100006'
}
item {
  id: 7
  name: 'Flannel'
  display_name: 'n0100007'
}
item {
  id: 8
  name: 'Halter'
  display_name: 'n0100008'
}
item {
  id: 9
  name: 'henley'
  display_name: 'n0100009'
}
item {
  id: 10
  name: 'hoodie'
  display_name: 'n0100010'
}
item {
  id: 11
  name: 'jacket'
  display_name: 'n0100011'
}
item {
  id: 12
  name: 'jersey'
  display_name: 'n0100012'
}
item {
  id: 13
  name: 'parka'
  display_name: 'n0100013'
}
item {
  id: 14
  name: 'peacoat'
  display_name: 'n0100014'
}
item {
  id: 15
  name: 'poncho'
  display_name: 'n0100015'
}
item {
  id: 16
  name: 'sweater'
  display_name: 'n0100016'
}
item {
  id: 17
  name: 'tank'
  display_name: 'n0100017'
}
item {
  id: 18
  name: 'tee'
  display_name: 'n0100018'
}
item {
  id: 19
  name: 'top'
  display_name: 'n0100019'
}
item {
  id: 20
  name: 'turtleneck'
  display_name: 'n0100020'
}
item {
  id: 21
  name: 'capris'
  display_name: 'n0100021'
}
item {
  id: 22
  name: 'chinos'
  display_name: 'n0100022'
}
item {
  id: 23
  name: 'culottes'
  display_name: 'n0100023'
}
item {
  id: 24
  name: 'cutoffs'
  display_name: 'n0100024'
}
item {
  id: 25
  name: 'gauchos'
  display_name: 'n0100025'
}
item {
  id: 26
  name: 'jeans'
  display_name: 'n0100026'
}
item {
  id: 27
  name: 'jeggings'
  display_name: 'n0100027'
}
item {
  id: 28
  name: 'jodhpurs'
  display_name: 'n0100028'
}
item {
  id: 29
  name: 'joggers'
  display_name: 'n0100029'
}
item {
  id: 30
  name: 'leggings'
  display_name: 'n0100030'
}
item {
  id: 31
  name: 'sarong'
  display_name: 'n0100031'
}
item {
  id: 32
  name: 'shorts'
  display_name: 'n0100032'
}
item {
  id: 33
  name: 'skirt'
  display_name: 'n0100033'
}
item {
  id: 34
  name: 'sweatpants'
  display_name: 'n0100034'
}
item {
  id: 35
  name: 'sweatshorts'
  display_name: 'n0100035'
}
item {
  id: 36
  name: 'trunks'
  display_name: 'n0100036'
}
item {
  id: 37
  name: 'caftan'
  display_name: 'n0100037'
}
item {
  id: 38
  name: 'cape'
  display_name: 'n0100038'
}
item {
  id: 39
  name: 'coat'
  display_name: 'n0100039'
}
item {
  id: 40
  name: 'coverup'
  display_name: 'n0100040'
}
item {
  id: 41
  name: 'dress'
  display_name: 'n0100041'
}
item {
  id: 42
  name: 'jumpsuit'
  display_name: 'n0100042'
}
item {
  id: 43
  name: 'kaftan'
  display_name: 'n0100043'
}
item {
  id: 44
  name: 'kimono'
  display_name: 'n0100044'
}
item {
  id: 45
  name: 'nightdress'
  display_name: 'n0100045'
}
item {
  id: 46
  name: 'onesie'
  display_name: 'n0100046'
}
item {
  id: 47
  name: 'robe'
  display_name: 'n0100047'
}
item {
  id: 48
  name: 'romper'
  display_name: 'n0100048'
}
item {
  id: 49
  name: 'shirtdress'
  display_name: 'n0100049'
}
item {
  id: 50
  name: 'sundress'
  display_name: 'n0100050'
}
item {
  id: 51
  name: 'jumper'
  display_name: 'n0100051'
}
item {
  id: 52
  name: 'yasang'
  display_name: 'n0100052'
}
item {
  id: 53
  name: 'padding'
  display_name: 'n0100053'
}
item {
  id: 54
  name: 'vest'
  display_name: 'n0100054'
}
item {
  id: 55
  name: 'shirts'
  display_name: 'n0100055'
}
item {
  id: 56
  name: 'mantoman'
  display_name: 'n0100056'
}
item {
  id: 57
  name: 'nasi'
  display_name: 'n0100057'
}
item {
  id: 58
  name: 'skinnypants'
  display_name: 'n0100058'
}
item {
  id: 59
  name: 'straightpants'
  display_name: 'n0100059'
}
item {
  id: 60
  name: 'slackspants'
  display_name: 'n0100060'
}
item {
  id: 61
  name: 'widepants'
  display_name: 'n0100061'
}
item {
  id: 62
  name: 'croppants'
  display_name: 'n0100062'
}
item {
  id: 63
  name: 'melbbangpants'
  display_name: 'n0100063'
}
item {
  id: 64
  name: 'skirtpants'
  display_name: 'n0100064'
}
item {
  id: 65
  name: 'miniskirt'
  display_name: 'n0100065'
}
item {
  id: 66
  name: 'midiskirt'
  display_name: 'n0100066'
}
item {
  id: 67
  name: 'longskirt'
  display_name: 'n0100067'
}
item {
  id: 68
  name: 'minionepiece'
  display_name: 'n0100068'
}
item {
  id: 69
  name: 'longonepiece'
  display_name: 'n0100069'
}
item {
  id: 70
  name: 'lingeriebra'
  display_name: 'n0100070'
}
item {
  id: 71
  name: 'lingeriepants'
  display_name: 'n0100071'
}
item {
  id: 72
  name: 'lingerieset'
  display_name: 'n0100072'
}
item {
  id: 73
  name: 'sleep'
  display_name: 'n0100073'
}
item {
  id: 74
  name: 'homewear'
  display_name: 'n0100074'
}
item {
  id: 75
  name: 'funtionalinner'
  display_name: 'n0100075'
}
item {
  id: 76
  name: 'innerpad'
  display_name: 'n0100076'
}
item {
  id: 77
  name: 'innerpants'
  display_name: 'n0100077'
}
item {
  id: 78
  name: 'bikini'
  display_name: 'n0100078'
}
item {
  id: 79
  name: 'onepieceswimsuit'
  display_name: 'n0100079'
}
item {
  id: 80
  name: 'monokini'
  display_name: 'n0100080'
}
item {
  id: 81
  name: 'rashguard'
  display_name: 'n0100081'
}
item {
  id: 82
  name: 'beachonepiece'
  display_name: 'n0100082'
}
item {
  id: 83
  name: 'beachtop'
  display_name: 'n0100083'
}
item {
  id: 84
  name: 'beachpants'
  display_name: 'n0100084'
}
item {
  id: 85
  name: 'couplewear'
  display_name: 'n0100085'
}
item {
  id: 86
  name: 'trainingtop'
  display_name: 'n0100086'
}
item {
  id: 87
  name: 'trainingpants'
  display_name: 'n0100087'
}
item {
  id: 88
  name: 'trainingset'
  display_name: 'n0100088'
}
item {
  id: 89
  name: 'trenchcoat'
  display_name: 'n0100089'
}
